### ISSUE TITLE
Capabilties don't support int ranges or "fake enums" 

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/openapi-extractor#16]
Define a capability as `recording-consent: int<0,2>` https://psalm.dev/docs/annotating_code/type_syntax/scalar_types/#int-range

```
Info: app: Extracting OpenAPI spec for spreed 18.0.0-dev.7
PHP Fatal error:  Uncaught Exception: Panic: ./lib/Capabilities.php: Unable to resolve OpenAPI type for type 'PHPStan\PhpDocParser\Ast\Type\GenericTypeNode'
 in apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/src/Logger.php:40
Stack trace:
#0 apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/src/OpenApiType.php(211): OpenAPIExtractor\Logger::panic()
#1 apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/src/OpenApiType.php(123): OpenAPIExtractor\OpenApiType::resolve()
#2 apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/src/OpenApiType.php(123): OpenAPIExtractor\OpenApiType::resolve()
#3 apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/src/OpenApiType.php(123): OpenAPIExtractor\OpenApiType::resolve()
#4 apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/src/OpenApiType.php(123): OpenAPIExtractor\OpenApiType::resolve()
#5 apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/src/OpenApiType.php(174): OpenAPIExtractor\OpenApiType::resolve()
#6 apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/generate-spec(198): OpenAPIExtractor\OpenApiType::resolve()
#7 apps/spreed/vendor/bin/generate-spec(119): include('...')
#8 {main}
  thrown in apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/src/Logger.php on line 40
Script generate-spec handling the openapi event returned with error code 255

```

Similarly `recording-consent: RecordingService::CONSENT_REQUIRED_*,` works in psalm, but crashes OpenAPI:
```
Info: app: Extracting OpenAPI spec for spreed 18.0.0-dev.7
PHP Fatal error:  Uncaught Exception: Panic: ./lib/Capabilities.php: Unable to resolve OpenAPI type for type 'PHPStan\PhpDocParser\Ast\Type\ConstTypeNode'
 in apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/src/Logger.php:40
Stack trace:
#0 apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/src/OpenApiType.php(211): OpenAPIExtractor\Logger::panic()
#1 apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/src/OpenApiType.php(123): OpenAPIExtractor\OpenApiType::resolve()
#2 apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/src/OpenApiType.php(123): OpenAPIExtractor\OpenApiType::resolve()
#3 apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/src/OpenApiType.php(123): OpenAPIExtractor\OpenApiType::resolve()
#4 apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/src/OpenApiType.php(123): OpenAPIExtractor\OpenApiType::resolve()
#5 apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/src/OpenApiType.php(174): OpenAPIExtractor\OpenApiType::resolve()
#6 apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/generate-spec(198): OpenAPIExtractor\OpenApiType::resolve()
#7 apps/spreed/vendor/bin/generate-spec(119): include('...')
#8 {main}
  thrown in apps/spreed/vendor-bin/openapi-extractor/vendor/nextcloud/openapi-extractor/src/Logger.php on line 40
Script generate-spec handling the openapi event returned with error code 255
```

Since restricting the values clarifies the API a lot, it would be helpful and cool to allow it.

**Comment by provokateurin** [comment]
The first problem should be easy to implement, but the second one is not possible since we can't resolve the class. You need to type it manually as a union type, but psalm can validate that this type is correct.
